### PR TITLE
PancakeSorting LeetCode Problem no. 969

### PR DESCRIPTION
**Pull request by sakshamdura**
pancake sorting in python3

### CODE REVIEW

**Comment by toakes59** [comment]
Looks good! Can you please rename the file to be 969_Pancake_Sorting.py

**Review by toakes59 — CHANGES_REQUESTED** [review]
Looks good! Can you please rename the file to be 969_Pancake_Sorting.py. Thanks for contributing!!

**Comment by sakshamdura** [comment]
Is it ok now?

**Review by toakes59 — APPROVED** [review]
Looks good! Thanks for contributing!

**Pull request merged**
